"""session advanced

Revision ID: 2da4cc53a3c6
Revises: acb59f483603
Create Date: 2025-04-21 13:41:58.139609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da4cc53a3c6'
down_revision = 'acb59f483603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advanced', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('advanced')

    # ### end Alembic commands ###
